### PR TITLE
fixes on the settings button and the positioning of the audio control tooltip

### PR DESCRIPTION
**Pull request by jzandag**
Issue #3!
here is the [Webapp link](https://jzandag.github.io/the-morse-code-project/) to my forked repo!

### CODE REVIEW

**Comment by ashuvssut** [comment]
@jzandag, Give PRs including the link to your version of the Webapp(github pages hosted) from your forked repo.

**Comment by jzandag** [comment]
hi @ashuvssut ! fixed

**Comment by ashuvssut** [comment]
image
this is how i want it to be

dont remove the  `box-shadow`

**Comment by ashuvssut** [comment]
this can be fixed by just adding `z-index:0;` to the tooltip.

**Comment by ashuvssut** [comment]
and also try to do a squash commit for your next push 😄

**Comment by ashuvssut** [comment]
You can add more issues so that other people can contribute and learn here!😁

**Comment by jzandag** [comment]
alright thanks for the feedback, please bear with me some of the terms are new to me ill learn them first asap

**Comment by ashuvssut** [comment]
Yeah sure take your time! I created these simple issues for learning purpose only😊

**Comment by jzandag** [comment]
@ashuvssut Hi, I fixed my previous code, thanks to that I also learned how to use git squash, Thanks for this opportunity!

**Comment by ashuvssut** [comment]
@jzandag  you have not performed the squash commit properly

image
I can still see that commit ID fa0096d. you havent squashed it yet.

```bash
# first go back (move HEAD) to your second last commit
git reset --soft HEAD~2 
# now head behind the two commits fa0096d and 67c07e3

# now perform commit to squash commit
git commit -m "new commit message"

#force push you new commit deleting  these two commits fa0096d and 67c07e3 on your forked remote repo
git push -f
```

After this you wont see that commit  fa0096d and 67c07e3 here in this PR.

Thats all.

always Squash commits when the commits you have made are totally undesirable. here, commit id fa0096d is undesirable

**Comment by ashuvssut** [comment]
For now, I will merge your PR. Coz, maintainers can also perform squash commit when merging a PR.

Keep contributing to opensource. there are lots of cool projects out there. Good Luck!

**Comment by jzandag** [comment]
@ashuvssut  thank you for this, I learned a lot in just short period of time!

**Pull request merged**
